import type { Metadata } from "next";
import { Inter  } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";


const inter = Inter({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background  grainy antialiased",
            inter.className
          )}
        >
          <Navbar/>
          {children}
          <Toaster richColors position="top-center" duration={1500}/>
        </body>
      </html>
    </ClerkProvider>
  );
}
